import it.unimi.dsi.mg4j.io.*;
import java.io.*;

/**
 * Test harness for output bitstream
 */
public class OutputBitstreamTest {
    public static void main( String[] args ) throws Exception {
        PrintStream ps = new PrintStream( new BufferedOutputStream( new FileOutputStream( "java_obs_log" )));

        byte[] dat = new byte[100];

        DebugOutputBitStream obs = new DebugOutputBitStream( new OutputBitStream( dat ), ps );

        // Call a bunch of methods.

        PrintWriter out = new PrintWriter(ps);
        obs.writeGamma( 5 );
        logArray( dat, out );
        obs.writeUnary( 0 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeZeta( 44, 5 );
        logArray( dat, out );
        obs.writeZeta( 15, 5 );
        logArray( dat, out );
        obs.writeZeta( 33, 5 );
        logArray( dat, out );
        obs.writeZeta( 2, 5 );
        logArray( dat, out );
        obs.writeZeta( 12, 5 );
        logArray( dat, out );
        obs.writeGamma( 1 );
        logArray( dat, out );
        obs.writeUnary( 0 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeZeta( 168, 5 );
        logArray( dat, out );
        obs.writeGamma( 12 );
        logArray( dat, out );
        obs.writeUnary( 0 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeZeta( 6, 5 );
        logArray( dat, out );
        obs.writeZeta( 5, 5 );
        logArray( dat, out );
        obs.writeZeta( 19, 5 );
        logArray( dat, out );
        obs.writeZeta( 7, 5 );
        logArray( dat, out );
        obs.writeZeta( 7, 5 );
        logArray( dat, out );
        obs.writeZeta( 0, 5 );
        logArray( dat, out );
        obs.writeZeta( 5, 5 );
        logArray( dat, out );
        obs.writeZeta( 17, 5 );
        logArray( dat, out );
        obs.writeZeta( 5, 5 );
        logArray( dat, out );
        obs.writeZeta( 2, 5 );
        logArray( dat, out );
        obs.writeZeta( 14, 5 );
        logArray( dat, out );
        obs.writeZeta( 2, 5 );
        logArray( dat, out );
        obs.writeGamma( 17 );
        logArray( dat, out );
        obs.writeUnary( 0 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeZeta( 8, 5 );
        logArray( dat, out );
        obs.writeZeta( 0, 5 );
        logArray( dat, out );
        obs.writeZeta( 1, 5 );
        logArray( dat, out );
        obs.writeZeta( 4, 5 );
        logArray( dat, out );
        obs.writeZeta( 5, 5 );
        logArray( dat, out );
        obs.writeZeta( 1, 5 );
        logArray( dat, out );
        obs.writeZeta( 0, 5 );
        logArray( dat, out );
        obs.writeZeta( 16, 5 );
        logArray( dat, out );
        obs.writeZeta( 2, 5 );
        logArray( dat, out );
        obs.writeZeta( 0, 5 );
        logArray( dat, out );
        obs.writeZeta( 5, 5 );
        logArray( dat, out );
        obs.writeZeta( 0, 5 );
        logArray( dat, out );
        obs.writeZeta( 11, 5 );
        logArray( dat, out );
        obs.writeZeta( 16, 5 );
        logArray( dat, out );
        obs.writeZeta( 1, 5 );
        logArray( dat, out );
        obs.writeZeta( 11, 5 );
        logArray( dat, out );
        obs.writeZeta( 0, 5 );
        logArray( dat, out );
        obs.writeGamma( 15 );
        logArray( dat, out );
        obs.writeUnary( 1 );
        logArray( dat, out );
        obs.writeGamma( 8 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeGamma( 3 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeGamma( 1 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeGamma( 5 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeZeta( 4, 5 );
        logArray( dat, out );
        obs.writeZeta( 15, 5 );
        logArray( dat, out );
        obs.writeZeta( 4, 5 );
        logArray( dat, out );
        obs.writeZeta( 8, 5 );
        logArray( dat, out );
        obs.writeZeta( 2, 5 );
        logArray( dat, out );
        obs.writeZeta( 3, 5 );
        logArray( dat, out );
        obs.writeZeta( 28, 5 );
        logArray( dat, out );
        obs.writeZeta( 4, 5 );
        logArray( dat, out );
        obs.writeZeta( 6, 5 );
        logArray( dat, out );
        obs.writeZeta( 6, 5 );
        logArray( dat, out );
        obs.writeGamma( 13 );
        logArray( dat, out );
        obs.writeUnary( 0 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeZeta( 7, 5 );
        logArray( dat, out );
        obs.writeZeta( 6, 5 );
        logArray( dat, out );
        obs.writeZeta( 1, 5 );
        logArray( dat, out );
        obs.writeZeta( 0, 5 );
        logArray( dat, out );
        obs.writeZeta( 5, 5 );
        logArray( dat, out );
        obs.writeZeta( 0, 5 );
        logArray( dat, out );
        obs.writeZeta( 32, 5 );
        logArray( dat, out );
        obs.writeZeta( 2, 5 );
        logArray( dat, out );
        obs.writeZeta( 4, 5 );
        logArray( dat, out );
        obs.writeZeta( 12, 5 );
        logArray( dat, out );
        obs.writeZeta( 14, 5 );
        logArray( dat, out );
        obs.writeZeta( 3, 5 );
        logArray( dat, out );
        obs.writeZeta( 4, 5 );
        logArray( dat, out );
        obs.writeGamma( 10 );
        logArray( dat, out );
        obs.writeUnary( 0 );
        logArray( dat, out );
        obs.writeGamma( 0 );
        logArray( dat, out );
        obs.writeZeta( 12, 5 );
        logArray( dat, out );
        obs.writeZeta( 4, 5 );
        logArray( dat, out );
        obs.writeZeta( 17, 5 );
        logArray( dat, out );
//         obs.writeZeta( 10, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 10, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 18 );
//         logArray( dat, out );
//         obs.writeUnary( 5 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 10, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 156, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 11 );
//         logArray( dat, out );
//         obs.writeUnary( 6 );
//         logArray( dat, out );
//         obs.writeGamma( 5 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 18, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 30, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 6 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 24, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 38, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 14 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 20, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 9 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 15, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 26, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 22, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 12 );
//         logArray( dat, out );
//         obs.writeUnary( 3 );
//         logArray( dat, out );
//         obs.writeGamma( 4 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 19, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 16, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 132, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 38, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 60, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 10 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 38 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 21, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 25, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 20, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 10, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 19 );
//         logArray( dat, out );
//         obs.writeUnary( 4 );
//         logArray( dat, out );
//         obs.writeGamma( 11 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 21, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 15, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 12 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 16, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 15, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 18 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 11 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 21, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 16, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 9 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 27, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 18, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 19, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 13 );
//         logArray( dat, out );
//         obs.writeUnary( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 9 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 43, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 58, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 19 );
//         logArray( dat, out );
//         obs.writeUnary( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 8 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 33, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 21, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 15, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 15 );
//         logArray( dat, out );
//         obs.writeUnary( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 5 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 4 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 122, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 9 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 29, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 8 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 17, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 19, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 17 );
//         logArray( dat, out );
//         obs.writeUnary( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 4 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 37, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 47, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 25, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 10 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 59, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 20, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 21, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 15, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 14 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 41, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 22, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 8 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 47, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 26, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 19, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 13 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 65, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 20, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 7 );
//         logArray( dat, out );
//         obs.writeUnary( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 3 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 4 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 30, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 15 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 51, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 18 );
//         logArray( dat, out );
//         obs.writeUnary( 3 );
//         logArray( dat, out );
//         obs.writeGamma( 8 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 4 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 53, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 15, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 23, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 3 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 65, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 19, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 72, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 102, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 19 );
//         logArray( dat, out );
//         obs.writeUnary( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 31 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 77, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 20, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 10, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 16, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 3 );
//         logArray( dat, out );
//         obs.writeUnary( 3 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 40, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 6 );
//         logArray( dat, out );
//         obs.writeUnary( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 6 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 11 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 25, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 14 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 85, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 37, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 13 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 63, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 10, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 19 );
//         logArray( dat, out );
//         obs.writeUnary( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 5 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 5 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 87, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 15, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 28, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 5 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 17, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 27, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 18, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 11 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 49, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 22, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 8 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 91, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 40, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 16, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 3 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 41, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 47, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 12 );
//         logArray( dat, out );
//         obs.writeUnary( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 4 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 91, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 19, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 21, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 19 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 91 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeZeta( 95, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 17, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 20, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 18, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 15 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 97, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 18, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 22, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 10, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 18 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 10 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeZeta( 97, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 10, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 31, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 18 );
//         logArray( dat, out );
//         obs.writeUnary( 8 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 4 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 77 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 99, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 21, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 17, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 13 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 27 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 71, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 18, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeUnary( 6 );
//         logArray( dat, out );
//         obs.writeGamma( 3 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 16 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 115, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 76, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 12 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 93, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 15, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 15, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 19, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 7 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 103, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 40, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 12 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 103, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 25, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 20, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 4 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 105, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 19, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 60, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 18 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 111, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 18 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 7 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeZeta( 119, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 22, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 16, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 12 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 119, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 10, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 5 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 97, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 23, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 21, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 6 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 55, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 16, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 8 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 131, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 20, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 19, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 10, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 11 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 135, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 9, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 16, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 16 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 141, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 10, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 2, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 3, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 7, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 13, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 18 );
//         logArray( dat, out );
//         obs.writeUnary( 3 );
//         logArray( dat, out );
//         obs.writeGamma( 5 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 3 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 135, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 6, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 18, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 14, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 5, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 12, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 7 );
//         logArray( dat, out );
//         obs.writeUnary( 6 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 47, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 0, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 26, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 4, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 3 );
//         logArray( dat, out );
//         obs.writeUnary( 5 );
//         logArray( dat, out );
//         obs.writeGamma( 3 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 18, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 11, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeUnary( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 8, 5 );
//         logArray( dat, out );
//         obs.writeGamma( 16 );
//         logArray( dat, out );
//         obs.writeUnary( 3 );
//         logArray( dat, out );
//         obs.writeGamma( 4 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 2 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeGamma( 1 );
//         logArray( dat, out );
//         obs.writeGamma( 15 );
//         logArray( dat, out );
//         obs.writeGamma( 0 );
//         logArray( dat, out );
//         obs.writeZeta( 135, 5 );
//         logArray( dat, out );
//         obs.writeZeta( 1, 5 );
//         logArray( dat, out );
        out.close();
    }

    public static void logArray( byte[] ary, PrintWriter pw ) {
        pw.print( "		" );
        
        for( int i = 0; i < ary.length; i++ ) {
            String str = Integer.toHexString( ary[i] );
            // only the last two digits count.
            str = str.substring( (int)Math.max(str.length() - 2, 0), str.length() );

            pw.print( str + " " );
        }

        pw.println();

        pw.flush();
    }
}
